2021-05-09 01:15:21,062 INFO    MainThread:24468 [internal.py:wandb_internal():91] W&B internal server running at pid: 24468, started at: 2021-05-09 01:15:21.061896
2021-05-09 01:15:21,064 INFO    WriterThread:24468 [datastore.py:open_for_write():77] open: /home/trenton-windows/repos/spicy-dann/wandb/offline-run-20210509_011520-2gtzw3ih/run-2gtzw3ih.wandb
2021-05-09 01:15:21,065 DEBUG   HandlerThread:24468 [handler.py:handle_request():121] handle_request: run_start
2021-05-09 01:15:21,096 DEBUG   HandlerThread:24468 [meta.py:__init__():39] meta init
2021-05-09 01:15:21,098 DEBUG   HandlerThread:24468 [meta.py:__init__():53] meta init done
2021-05-09 01:15:21,098 DEBUG   HandlerThread:24468 [meta.py:probe():210] probe
2021-05-09 01:15:21,100 DEBUG   HandlerThread:24468 [meta.py:_setup_git():200] setup git
2021-05-09 01:15:21,111 DEBUG   HandlerThread:24468 [meta.py:_setup_git():207] setup git done
2021-05-09 01:15:21,111 DEBUG   HandlerThread:24468 [meta.py:_save_pip():57] save pip
2021-05-09 01:15:21,111 DEBUG   HandlerThread:24468 [meta.py:_save_pip():71] save pip done
2021-05-09 01:15:21,111 DEBUG   HandlerThread:24468 [meta.py:_save_conda():78] save conda
2021-05-09 01:15:23,183 DEBUG   HandlerThread:24468 [meta.py:_save_conda():86] save conda done
2021-05-09 01:15:23,183 DEBUG   HandlerThread:24468 [meta.py:probe():252] probe done
2021-05-09 01:18:05,899 WARNING MainThread:24468 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-05-09 01:18:06,090 WARNING MainThread:24468 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-05-09 01:18:06,091 ERROR   MainThread:24468 [internal.py:wandb_internal():150] Internal process interrupted.
2021-05-09 01:18:06,119 INFO    SenderThread:24468 [sender.py:finish():925] shutting down sender
2021-05-09 01:18:06,473 INFO    WriterThread:24468 [datastore.py:close():258] close: /home/trenton-windows/repos/spicy-dann/wandb/offline-run-20210509_011520-2gtzw3ih/run-2gtzw3ih.wandb
2021-05-09 01:18:06,474 INFO    MainThread:24468 [internal.py:handle_exit():78] Internal process exited
