2021-05-09 01:50:11,559 INFO    MainThread:27006 [internal.py:wandb_internal():91] W&B internal server running at pid: 27006, started at: 2021-05-09 01:50:11.559163
2021-05-09 01:50:11,564 INFO    WriterThread:27006 [datastore.py:open_for_write():77] open: /home/trenton-windows/repos/spicy-dann/wandb/offline-run-20210509_015010-2bgdydpu/run-2bgdydpu.wandb
2021-05-09 01:50:11,564 DEBUG   HandlerThread:27006 [handler.py:handle_request():121] handle_request: run_start
2021-05-09 01:50:11,605 DEBUG   HandlerThread:27006 [meta.py:__init__():39] meta init
2021-05-09 01:50:11,605 DEBUG   HandlerThread:27006 [meta.py:__init__():53] meta init done
2021-05-09 01:50:11,605 DEBUG   HandlerThread:27006 [meta.py:probe():210] probe
2021-05-09 01:50:11,607 DEBUG   HandlerThread:27006 [meta.py:_setup_git():200] setup git
2021-05-09 01:50:11,621 DEBUG   HandlerThread:27006 [meta.py:_setup_git():207] setup git done
2021-05-09 01:50:11,621 DEBUG   HandlerThread:27006 [meta.py:_save_pip():57] save pip
2021-05-09 01:50:11,622 DEBUG   HandlerThread:27006 [meta.py:_save_pip():71] save pip done
2021-05-09 01:50:11,622 DEBUG   HandlerThread:27006 [meta.py:_save_conda():78] save conda
2021-05-09 01:50:13,839 DEBUG   HandlerThread:27006 [meta.py:_save_conda():86] save conda done
2021-05-09 01:50:13,840 DEBUG   HandlerThread:27006 [meta.py:probe():252] probe done
2021-05-09 01:53:49,371 WARNING MainThread:27006 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-05-09 01:56:34,715 WARNING MainThread:27006 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-05-09 01:56:34,715 ERROR   MainThread:27006 [internal.py:wandb_internal():150] Internal process interrupted.
2021-05-09 01:56:35,481 INFO    WriterThread:27006 [datastore.py:close():258] close: /home/trenton-windows/repos/spicy-dann/wandb/offline-run-20210509_015010-2bgdydpu/run-2bgdydpu.wandb
2021-05-09 01:56:35,643 INFO    SenderThread:27006 [sender.py:finish():925] shutting down sender
2021-05-09 01:56:35,645 INFO    MainThread:27006 [internal.py:handle_exit():78] Internal process exited
