2021-05-09 01:18:16,542 INFO    MainThread:24704 [internal.py:wandb_internal():91] W&B internal server running at pid: 24704, started at: 2021-05-09 01:18:16.542218
2021-05-09 01:18:16,555 DEBUG   HandlerThread:24704 [handler.py:handle_request():121] handle_request: run_start
2021-05-09 01:18:16,555 INFO    WriterThread:24704 [datastore.py:open_for_write():77] open: /home/trenton-windows/repos/spicy-dann/wandb/offline-run-20210509_011815-2i13in6u/run-2i13in6u.wandb
2021-05-09 01:18:16,614 DEBUG   HandlerThread:24704 [meta.py:__init__():39] meta init
2021-05-09 01:18:16,614 DEBUG   HandlerThread:24704 [meta.py:__init__():53] meta init done
2021-05-09 01:18:16,614 DEBUG   HandlerThread:24704 [meta.py:probe():210] probe
2021-05-09 01:18:16,615 DEBUG   HandlerThread:24704 [meta.py:_setup_git():200] setup git
2021-05-09 01:18:16,628 DEBUG   HandlerThread:24704 [meta.py:_setup_git():207] setup git done
2021-05-09 01:18:16,629 DEBUG   HandlerThread:24704 [meta.py:_save_pip():57] save pip
2021-05-09 01:18:16,629 DEBUG   HandlerThread:24704 [meta.py:_save_pip():71] save pip done
2021-05-09 01:18:16,629 DEBUG   HandlerThread:24704 [meta.py:_save_conda():78] save conda
2021-05-09 01:18:19,635 DEBUG   HandlerThread:24704 [meta.py:_save_conda():86] save conda done
2021-05-09 01:18:19,635 DEBUG   HandlerThread:24704 [meta.py:probe():252] probe done
2021-05-09 01:22:58,765 WARNING MainThread:24704 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-05-09 01:22:58,930 WARNING MainThread:24704 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-05-09 01:22:58,930 ERROR   MainThread:24704 [internal.py:wandb_internal():150] Internal process interrupted.
2021-05-09 01:22:59,497 INFO    WriterThread:24704 [datastore.py:close():258] close: /home/trenton-windows/repos/spicy-dann/wandb/offline-run-20210509_011815-2i13in6u/run-2i13in6u.wandb
2021-05-09 01:22:59,612 INFO    SenderThread:24704 [sender.py:finish():925] shutting down sender
2021-05-09 01:22:59,613 INFO    MainThread:24704 [internal.py:handle_exit():78] Internal process exited
